import React from 'react'

function ProductAE4() {
  return (
    <div >
    <table cellPadding="1" cellSpacing="1">
        <tbody><tr><td colSpan="4">الموديل</td> <td>CPD16SA3</td> <td>CPD18SA3</td> <td>CPD20SA3</td> </tr> <tr> <td>الحمل المقنن</td> <td colSpan="2">&nbsp;</td> <td>kg</td> <td>1600</td> <td>1800</td> <td>2000</td> </tr> <tr> <td>مسافة مركز الحمل</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>500</td> <td>500</td> <td>500</td> </tr> <tr> <td>إرتفاع الرفع</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>3000</td> <td>3000</td> <td>3000</td> </tr> <tr> <td>الإرتفاع الحر للرفع</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>150</td> <td>150</td> <td>150</td> </tr> <tr> <td>قياس الشوكة</td> <td>&nbsp;</td> <td>L×W×T</td> <td>mm</td> <td colSpan="2">1070×100×40</td> <td>1070×122×40</td> </tr> <tr> <td>زاوية ميول الصاري</td> <td>&nbsp;</td> <td>FR/RR</td> <td>。</td> <td>6.5/6.5</td> <td>6.5/6.5</td> <td>6.5/6.5</td> </tr> <tr> <td>أقل نصف قطر للدوران</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>1550</td> <td>1550</td> <td>1680</td> </tr> <tr> <td>أقل عرض لممر التكديس للزاوية اليمنى</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>3070</td> <td>3070</td> <td>3220</td> </tr> <tr> <td>أدنى مسافة عن الأرض</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>102</td> <td>102</td> <td>100</td> </tr> <tr> <td>إرتفاع واقي الحماية العلوي</td> <td colSpan="2">&nbsp;</td> <td>mm</td> <td>1960</td> <td>1960</td> <td>2020</td> </tr> <tr> <td rowspan="3">الأداء</td> <td>أقصى سرعة للتنقل</td> <td>حمل كامل</td> <td>km/h</td> <td>14</td> <td>14</td> <td>13</td> </tr> <tr> <td>أقصى سرعة للرفع</td> <td>حمل كامل</td> <td>mm/s</td> <td>260</td> <td>260</td> <td>200</td> </tr> <tr> <td colSpan="2">أقصى قدرة للصعود</td> <td>%</td> <td>15</td> <td>15</td> <td>15</td> </tr> <tr> <td rowspan="2">الأبعاد</td> <td>الطول الكلي</td> <td>بدون شوكة</td> <td>mm</td> <td>1930</td> <td>1930</td> <td>2080</td> </tr> <tr> <td colSpan="2">العرض الكلي</td> <td>mm</td> <td>1066</td> <td>1066</td> <td>1156</td> </tr> <tr> <td>الوزن الذاتي</td> <td>&nbsp;</td> <td>بدون حمل</td> <td>kg</td> <td>3200</td> <td>3260</td> <td>3550</td> </tr> <tr> <td>البطارية</td> <td>&nbsp;</td> <td>جهد\تردد</td> <td>V/Ah</td> <td>48/500</td> <td>48/500</td> <td>48/560</td> </tr> <tr> <td rowspan="2">المحرك</td> <td>&nbsp;</td> <td>التنقل</td> <td>kW</td> <td>4.8×2</td> <td>4.8×2</td> <td>4.8×2</td> </tr> <tr> <td>الرفع</td> <td>&nbsp;</td> <td>kW</td> <td>10</td> <td>10</td> <td>10</td> </tr> <tr> <td colSpan="4">طرق التحكم</td> <td>AC</td> <td>AC</td> <td>AC</td> </tr> <tr> <td colSpan="3">ضغط التشغيل</td> <td>Mpa</td> <td>15.5</td> <td>15.5</td> <td>15.5</td> </tr> <tr> <td colSpan="3">أقصى سحب لقضيب الجر</td> <td>kN</td> <td>18</td> <td>18</td> <td>14</td>  </tr>
    </tbody></table>
</div>
  )
}

export default ProductAE4